// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: author.sql

package db

import (
	"context"

	"github.com/lib/pq"
)

const createAuthor = `-- name: CreateAuthor :one
INSERT INTO authors (
  name, 
  biography
) VALUES (
  $1, $2
)
RETURNING id, name, biography, books
`

type CreateAuthorParams struct {
	Name      string `json:"name"`
	Biography string `json:"biography"`
}

func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Author, error) {
	row := q.db.QueryRowContext(ctx, createAuthor, arg.Name, arg.Biography)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Biography,
		pq.Array(&i.Books),
	)
	return i, err
}

const deleteAuthor = `-- name: DeleteAuthor :one
DELETE FROM authors
WHERE id = $1
RETURNING id, name, biography, books
`

func (q *Queries) DeleteAuthor(ctx context.Context, id int64) (Author, error) {
	row := q.db.QueryRowContext(ctx, deleteAuthor, id)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Biography,
		pq.Array(&i.Books),
	)
	return i, err
}

const getAuthor = `-- name: GetAuthor :one
SELECT id, name, biography, books FROM authors
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAuthor(ctx context.Context, id int64) (Author, error) {
	row := q.db.QueryRowContext(ctx, getAuthor, id)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Biography,
		pq.Array(&i.Books),
	)
	return i, err
}

const listAuthors = `-- name: ListAuthors :many
SELECT id, name, biography, books FROM authors
ORDER BY id
`

func (q *Queries) ListAuthors(ctx context.Context) ([]Author, error) {
	rows, err := q.db.QueryContext(ctx, listAuthors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Author
	for rows.Next() {
		var i Author
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Biography,
			pq.Array(&i.Books),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAuthor = `-- name: UpdateAuthor :one
UPDATE authors
set name = $2,
biography = $3
WHERE id = $1
RETURNING id, name, biography, books
`

type UpdateAuthorParams struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	Biography string `json:"biography"`
}

func (q *Queries) UpdateAuthor(ctx context.Context, arg UpdateAuthorParams) (Author, error) {
	row := q.db.QueryRowContext(ctx, updateAuthor, arg.ID, arg.Name, arg.Biography)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Biography,
		pq.Array(&i.Books),
	)
	return i, err
}
