// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import ()

type Author struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	Biography string `json:"biography"`
}

type Book struct {
	ID       int64   `json:"id"`
	Title    string  `json:"title"`
	Author   int64   `json:"author"`
	Category int64   `json:"category"`
	Price    float64 `json:"price"`
}

type Category struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}
